name: CI

on:
  push:
    branches: '**'
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    name: Test Node.js ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [14, 16]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - run: pnpm --version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'

      - run: node --version

      - run: pnpm install

      - run: pnpm test

      - run: pnpm lint
